PrincipalBundle\Entity\Companias:
    type: entity
    table: companias
    id:
        numCompania:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: num_compania
            generator:
                strategy: IDENTITY
    fields:
        actividad:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
