PrincipalBundle\Entity\CuerposEjercito:
    type: entity
    table: cuerpos_ejercito
    id:
        codigoCuerpo:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigo_cuerpo
            generator:
                strategy: IDENTITY
    fields:
        denominacion:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
